baseURL: https://j605.tk/blog
disablePathToLower: true
languageCode: en-us
title: Jagan's blog
theme: zen
pygmentsCodefences: true
pygmentsStyle: native

params:
  contact: "info@example.org"
  # copyright: "This site is licensed under a (https://creativecommons.org/licenses/by-sa/4.0/)."
              # [Creative Commons Attribution-ShareAlike 4.0 International License]
  dateformat: ""            # Set the date format, default to "2 January, 2006"
  description: ""           # Set site description, used in meta tags and JSON-LD
  feedlinks: true           # Show feed links in the footer.
  poweredby: true           # Show powered by hugo in footer
  sidebar: true             # Show a sidebar to the right
  submitted: true           # Show author and date information for a post.
